version: "3.8"

# This Compose file defines two services: app and db
# The app service uses an image that’s built from the 
# Dockerfile in the current directory. It then binds the 
# container and the host machine to the exposed port, 5000. 
# The app service uses the default port for the Flask web 
# server, 5000.

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/code

# The volumes key above mounts the project directory 
# (current directory) on the host to /code inside the 
# container, allowing you to modify the code on the fly, 
# without having to rebuild the image. 

  db:
    image: postgres:13.2
    volumes:
      - ../data:/var/lib/postgresql/data
    env_file:
      - .env

# The image option above specifies what Docker image to use. 
# Here we're using version 13.2 of the official Postgres image.

# For the volumes option we are mapping a local folder called 
# data to a folder inside the container at 
# /var/lib/postgresql/data


