"""Add vendor id to healthchecks

Revision ID: 2da619a287f6
Revises: 563f67ae5e54
Create Date: 2022-08-15 11:42:22.802618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da619a287f6'
down_revision = '563f67ae5e54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_checks', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'health_checks', 'vendors', ['vendor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'health_checks', type_='foreignkey')
    op.drop_column('health_checks', 'vendor_id')
    # ### end Alembic commands ###
