"""empty message

Revision ID: 9c60c12ee226
Revises: b28b8509c6e6
Create Date: 2022-07-23 15:27:12.665772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c60c12ee226'
down_revision = 'b28b8509c6e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_groups', sa.Column('device_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'check_groups', 'devices', ['device_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'check_groups', type_='foreignkey')
    op.drop_column('check_groups', 'device_id')
    # ### end Alembic commands ###
