"""empty message

Revision ID: b28b8509c6e6
Revises: 33fac10cbdf9
Create Date: 2022-07-23 15:13:18.147290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28b8509c6e6'
down_revision = '33fac10cbdf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_groups_uuid_key', 'check_groups', type_='unique')
    op.drop_column('check_groups', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_groups', sa.Column('uuid', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.create_unique_constraint('check_groups_uuid_key', 'check_groups', ['uuid'])
    # ### end Alembic commands ###
