"""empty message

Revision ID: e272bb056996
Revises: eafcee5fafc0
Create Date: 2022-08-17 12:00:48.413915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e272bb056996'
down_revision = 'eafcee5fafc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('health_checks_device_id_fkey', 'health_checks', type_='foreignkey')
    op.drop_column('health_checks', 'device_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_checks', sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('health_checks_device_id_fkey', 'health_checks', 'devices', ['device_id'], ['id'])
    # ### end Alembic commands ###
