"""Add Netmiko Alias to the Vendor model

Revision ID: eafcee5fafc0
Revises: 2da619a287f6
Create Date: 2022-08-15 23:43:39.488546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eafcee5fafc0'
down_revision = '2da619a287f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('netmiko_alias', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'netmiko_alias')
    # ### end Alembic commands ###
